server:
  port: 8083
spring:
  datasource:
    username: root
    password: 13458264160

  servlet:
    multipart:
      enabled: true
      # 设置文件大小限制
      max-file-size: 10240000000
      # 设置总上传数据总大小
      max-request-size: 30720000000